# Generated by Django 5.0.3 on 2024-07-09 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FootBall", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_plyer",
                to="FootBall.player",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("start", "start"),
                    ("goal", "goal"),
                    ("corner", "corner"),
                    ("foul", "foul"),
                    ("penalty", "penalty"),
                    ("offside", "offside"),
                    ("red", "red card"),
                    ("yellow", "yellow card"),
                ],
                default="None",
                max_length=40,
            ),
        ),
    ]
