# Generated by Django 5.0.3 on 2024-07-23 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FootBall", "0003_remove_team_status_remove_team_user_team_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="serial_number",
        ),
        migrations.RemoveField(
            model_name="player",
            name="serial_number",
        ),
        migrations.RemoveField(
            model_name="referee",
            name="serial_number",
        ),
        migrations.RemoveField(
            model_name="teamstats",
            name="serial_number",
        ),
    ]
