# Generated by Django 5.0.3 on 2024-07-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FootBall", "0004_remove_match_serial_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_time",
            field=models.PositiveIntegerField(
                blank=True, default="None", help_text="Time in minutes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("start", "start"),
                    ("goal", "goal"),
                    ("corner", "corner"),
                    ("foul", "foul"),
                    ("penalty", "penalty"),
                    ("offside", "offside"),
                    ("red", "red card"),
                    ("yellow", "yellow card"),
                ],
                default="None",
                max_length=40,
                null=True,
            ),
        ),
    ]
