# Generated by Django 5.0.3 on 2024-07-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FootBall", "0005_alter_event_event_time_alter_event_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_time",
            field=models.PositiveIntegerField(
                blank=True, default=0, help_text="Time in minutes", null=True
            ),
        ),
    ]
